name: Adw-gtk3 issue template
description: Use this template to report issues with the theme.
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: To rule out invalid issues, confirm and check each one of the checkboxes.
      options:
        - label: I performed a [cursory search of the issue tracker](https://github.com/LSeelig/adw-gtk3-white-headers/issues?q=is%3Aissue) to avoid opening a duplicate issue.
          required: true

  - type: checkboxes
    attributes:
      label: Checklist to make sure the issue is not on your end
      options:
        - label: I have made sure that I do not have multiple versions of the theme installed. Only one version should be installed in either `~/.local/share/themes` or `/usr/share/themes`
          required: true
        - label: The files `~/.config/gtk-3.0/gtk.css` and `~/.config/gtk-4.0/gtk.css` does not exist. (Backup and remove those files and restart any apps.)
          required: true
        - label: I've made sure that the issue did not go away by restarting apps or by logging out and in again.
          required: true
        - label: By running the command `env` I've made sure that there is no environment variable called `GTK_THEME`
          required: false
        - label: The app I'm having an issue with is installed with flatpak. I've installed the theme in `~/.local/share/themes` and ran the command `sudo flatpak override --filesystem=xdg-data/themes`
          required: false

  - type: checkboxes
    attributes:
      label: Installation method
      options:
        - label: Tarball
          required: false
        - label: Source
          required: false
        - label: Other (Specify)
          required: false

  - type: textarea
    attributes:
      label: Description
      description: | 
        Provide a clear and concise description of the issue.
        Screenshot(s) are good to have for hard-to-describe visual issues.
        Post **LINKS** instead of inline images for screenshots containing **ADULT MATERIAL**.
    validations:
      required: true

  - type: input
    attributes:
      label: OS and version [e.g Fedora 42]
    validations:
      required: true

  - type: input
    attributes:
      label: Adw-gtk3-wh version/commit.
    validations:
      required: true

  - type: input
    attributes:
      label: GNOME version
    validations:
      required: false

  - type: input
    attributes:
      label: Application name and version. (Note that minor issues with single applications have a very low priority.)
    validations:
      required: false

